/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InvoiceMenu.java
 *
 * Created on 07-ago-2011, 14:56:37
 */
package itla.jpuppy.forms;

import itla.jpuppy.controllers.ControllerInvoices;
import itla.jpuppy.models.SearchingModel;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Jordhano
 */
public class InvoiceMenu extends javax.swing.JFrame implements FrameOption {

    /** Creates new form InvoiceMenu */
    private JSearching searching;
    private ControllerInvoices ctrlInvoices;
    public InvoiceMenu() {
        initComponents();
        ctrlInvoices = new ControllerInvoices(this);
        searching.setBounds(12, 145,877, 182);
        this.add(searching);
        this.setTitle("Facturacion");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setListener();
    }
    
    public void setListener(){
        searching.getTxtSearch().addKeyListener(ctrlInvoices);
        searching.getTblResult().addMouseListener(ctrlInvoices);
        tblMyArticles.addMouseListener(ctrlInvoices);
        tblMyArticles.addKeyListener(ctrlInvoices);
        
        btnNew.addActionListener(ctrlInvoices);
        btnSave.addActionListener(ctrlInvoices);
//        btnSearchInvoice.addActionListener(ctrlInvoices);
        btnSearch.addActionListener(ctrlInvoices);
        btnExit.addActionListener(ctrlInvoices);
    }

    public void setCustomerFields(String txtAdress, String txtCodeCustomer, String txtName) {
        this.txtAdress.setText(txtAdress);
        this.txtCodeCustomer.setText(txtCodeCustomer);
        this.txtName.setText(txtName);
    }

    public JTextField getTxtDateInvoice() {
        return txtDateInvoice;
    }

    public JTextField getTxtNoInvoice() {
        return txtNoInvoice;
    }
    
    public JButton getBtnExit() {
        return btnExit;
    }

    public JButton getBtnNew() {
        return btnNew;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public JButton getBtnSearch() {
        return btnSearch;
    }

    public JPanel getPnlCustomerInfo() {
        return pnlCustomerInfo;
    }

    public JPanel getPnlInvoiceInfo() {
        return pnlInvoiceInfo;
    }

    public JSearching getSearching() {
        return searching;
    }

    public JTextField getTxtTotal() {
        return txtTotal;
    }

    public void setSearching(JSearching searching) {
        this.searching = searching;
    }

    public void setTxtTotal(String txtTotal) {
        this.txtTotal.setText(txtTotal);
    }

    public JTable getTblMyArticles() {
        return tblMyArticles;
    }

    public void setTblMyArticles(JTable tblMyArticles) {
        this.tblMyArticles = tblMyArticles;
    }
    
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInvoiceInfo = new javax.swing.JPanel();
        lblNoInvoice = new javax.swing.JLabel();
        lblDateInvoice = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtNoInvoice = new javax.swing.JTextField();
        txtDateInvoice = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        pnlCustomerInfo = new javax.swing.JPanel();
        lblCodeCustomer = new javax.swing.JLabel();
        txtCodeCustomer = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAdress = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        pnlOptions = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblTotalLabel = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMyArticles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlInvoiceInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNoInvoice.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblNoInvoice.setText("No.Factura.:");

        lblDateInvoice.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblDateInvoice.setText("Fecha.:");

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblUser.setText("Usuario.:");

        txtNoInvoice.setFont(new java.awt.Font("Tahoma", 0, 14));
        txtNoInvoice.setEnabled(false);

        txtDateInvoice.setFont(new java.awt.Font("Tahoma", 0, 14));
        txtDateInvoice.setEnabled(false);

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 14));
        txtUser.setEnabled(false);

        javax.swing.GroupLayout pnlInvoiceInfoLayout = new javax.swing.GroupLayout(pnlInvoiceInfo);
        pnlInvoiceInfo.setLayout(pnlInvoiceInfoLayout);
        pnlInvoiceInfoLayout.setHorizontalGroup(
            pnlInvoiceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoiceInfoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(pnlInvoiceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInvoiceInfoLayout.createSequentialGroup()
                        .addComponent(lblNoInvoice)
                        .addGap(10, 10, 10)
                        .addComponent(txtNoInvoice))
                    .addGroup(pnlInvoiceInfoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInvoiceInfoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblDateInvoice)
                        .addGap(10, 10, 10)
                        .addComponent(txtDateInvoice)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        pnlInvoiceInfoLayout.setVerticalGroup(
            pnlInvoiceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoiceInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInvoiceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoInvoice)
                    .addComponent(txtNoInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlInvoiceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDateInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateInvoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInvoiceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pnlCustomerInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCodeCustomer.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblCodeCustomer.setText("Codigo.:");

        txtCodeCustomer.setFont(new java.awt.Font("Tahoma", 0, 14));
        txtCodeCustomer.setEnabled(false);

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblName.setText("Nombre.:");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14));
        txtName.setEnabled(false);

        lblAdress.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblAdress.setText("Dirrecion.:");

        txtAdress.setFont(new java.awt.Font("Tahoma", 0, 14));
        txtAdress.setEnabled(false);

        btnSearch.setText("Buscar");
        btnSearch.setFocusable(false);

        javax.swing.GroupLayout pnlCustomerInfoLayout = new javax.swing.GroupLayout(pnlCustomerInfo);
        pnlCustomerInfo.setLayout(pnlCustomerInfoLayout);
        pnlCustomerInfoLayout.setHorizontalGroup(
            pnlCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerInfoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCustomerInfoLayout.createSequentialGroup()
                        .addGroup(pnlCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblCodeCustomer))
                        .addGap(5, 5, 5))
                    .addComponent(lblAdress))
                .addGap(28, 28, 28)
                .addGroup(pnlCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAdress)
                    .addComponent(txtName)
                    .addComponent(txtCodeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addContainerGap())
        );
        pnlCustomerInfoLayout.setVerticalGroup(
            pnlCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCustomerInfoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtCodeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCustomerInfoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblName))
                    .addComponent(lblCodeCustomer)
                    .addGroup(pnlCustomerInfoLayout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addGap(35, 35, 35)
                        .addComponent(lblAdress)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlOptions.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itla/jpuppy/resources/add.png"))); // NOI18N
        btnNew.setFocusable(false);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itla/jpuppy/resources/save.png"))); // NOI18N
        btnSave.setFocusable(false);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itla/jpuppy/resources/cancel.png"))); // NOI18N
        btnExit.setFocusable(false);

        lblTotalLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblTotalLabel.setText("Total.:");

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 18));
        txtTotal.setEnabled(false);

        javax.swing.GroupLayout pnlOptionsLayout = new javax.swing.GroupLayout(pnlOptions);
        pnlOptions.setLayout(pnlOptionsLayout);
        pnlOptionsLayout.setHorizontalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(lblTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlOptionsLayout.setVerticalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, 0, 0, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE)
                    .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTotalLabel)))
                .addContainerGap())
        );

        tblMyArticles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMyArticles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlOptions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pnlInvoiceInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCustomerInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInvoiceInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblCodeCustomer;
    private javax.swing.JLabel lblDateInvoice;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNoInvoice;
    private javax.swing.JLabel lblTotalLabel;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlCustomerInfo;
    private javax.swing.JPanel pnlInvoiceInfo;
    private javax.swing.JPanel pnlOptions;
    private javax.swing.JTable tblMyArticles;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtCodeCustomer;
    private javax.swing.JTextField txtDateInvoice;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNoInvoice;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    
    
    @Override
    public void showFrame() {
       this.setVisible(true);
    }

    @Override
    public void closeFrame() {
        dispose();
    }
    
     @Override
    public void dispose() {
        itla.jpuppy.business.EntityManagerCreator.close();
        super.dispose();
    }
}
